project:
  type: book
  output-dir: _site

book:
  title: "Manual de Python"
  author: "Docente"
  date: today
  chapters:
    - index.qmd
    - chapters/01-empezando-en-python.qmd
    - chapters/02-objetos-en-python.qmd
    - chapters/03-datos-externos.qmd
    - chapters/04-graficos-basicos-matplotlib.qmd
    - chapters/05-estadisticas-descriptivas.qmd
    - chapters/06-distribuciones-de-probabilidad.qmd
    - chapters/07-intervalos-de-confianza-e-inferencia.qmd
    - chapters/08-python-avanzado-condicionales-bucles-funciones-sympy.qmd
    - chapters/09-simulacion-monte-carlo.qmd
    - chapters/99-glosario-general.qmd




format:
  html:
    toc: true
    toc-depth: 3
    number-sections: False
    code-copy: true
    code-overflow: wrap
  pdf:
    toc: true
    number-sections: False
    documentclass: scrreprt

execute:
  echo: true
  warning: false
  message: false
  error: false
  freeze: auto
